//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MET01_TIPO_USUARIO
    {
        public MET01_TIPO_USUARIO()
        {
            this.MET01_USUARIO = new HashSet<MET01_USUARIO>();
        }
    
        public decimal TIPO_USUARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<MET01_USUARIO> MET01_USUARIO { get; set; }
    }
}
