//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MET01_RECIBO
    {
        public decimal RECIBO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string TOTAL_LETRAS { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<decimal> EVENTO { get; set; }
        public Nullable<decimal> IGLESIA { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual MET01_EVENTO MET01_EVENTO { get; set; }
        public virtual MET01_IGLESIA MET01_IGLESIA { get; set; }
    }
}
