//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MET01_ENCARGADO
    {
        public MET01_ENCARGADO()
        {
            this.MET01_IGLESIA = new HashSet<MET01_IGLESIA>();
        }
    
        public decimal ENCARGADO { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string TALLA { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<MET01_IGLESIA> MET01_IGLESIA { get; set; }
    }
}
