//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET01.DO.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesMetro : DbContext
    {
        public EntitiesMetro()
            : base("name=EntitiesMetro")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MET01_ENCARGADO> MET01_ENCARGADO { get; set; }
        public DbSet<MET01_EVENTO> MET01_EVENTO { get; set; }
        public DbSet<MET01_IGLESIA> MET01_IGLESIA { get; set; }
        public DbSet<MET01_PASTOR> MET01_PASTOR { get; set; }
        public DbSet<MET01_RECIBO> MET01_RECIBO { get; set; }
        public DbSet<MET01_REGION> MET01_REGION { get; set; }
        public DbSet<MET01_TIPO_USUARIO> MET01_TIPO_USUARIO { get; set; }
        public DbSet<MET01_USUARIO> MET01_USUARIO { get; set; }
        public DbSet<MET01_RECIBO_OFICINA> MET01_RECIBO_OFICINA { get; set; }
        public DbSet<MET01_CORRELATIVO> MET01_CORRELATIVO { get; set; }
        public DbSet<MET01_ESTADO> MET01_ESTADO { get; set; }
    }
}
