//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET01.UI.testData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MET01_IGLESIA
    {
        public decimal IGLESIA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> REGION { get; set; }
        public Nullable<decimal> ENCARGADO { get; set; }
        public Nullable<decimal> PASTOR { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual MET01_ENCARGADO MET01_ENCARGADO { get; set; }
        public virtual MET01_PASTOR MET01_PASTOR { get; set; }
        public virtual MET01_REGION MET01_REGION { get; set; }
    }
}
