//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET01.UI.testData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MET01_PASTOR
    {
        public MET01_PASTOR()
        {
            this.MET01_IGLESIA = new HashSet<MET01_IGLESIA>();
        }
    
        public decimal PASTOR { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<MET01_IGLESIA> MET01_IGLESIA { get; set; }
    }
}
